### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by pecourses** [Ms-Julia30/Block-Model-Project#3]
https://github.com/Ms-Julia30/Block-Model-Project/blob/25c10795bfd4949dcff025d14e8f5018f127b8c0/style.css#L70-L82
- по факту, ці дві області дуже схожі, відрізняються тільки кольорами тексту і тла. Тому в таких випадках спільні втастивості збирають разом і описують один раз - не повторюються (принцип DRY - don`t repeat youself). Тоді при підтримці коду, якщо, приміром, треба змінити падінг, ми будемо вносити зміни не в обидва набори стилів, а в один:
```css
.block-three ,
.block-three-white {
    display: inline-block;
    padding: 15px;
    width: 33.33%;
}

.block-three {
    color: white;
    background-color: rgb(146, 98, 57);
}
```
